name: flutter_application_1
description: "A new Flutter project."

version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  fl_chart: ^0.69.0
  http: ^0.13.4 
  charts_flutter: ^0.12.0 
  expressions: ^0.2.3


  flutter:
    sdk: flutter
  provider: ^6.0.0 
  
  csv: ^6.0.0
  file_picker: ^4.6.1
  path_provider: ^2.0.10
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
